//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportCMSLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customers()
        {
            this.Billings = new HashSet<Billings>();
            this.Warnings = new HashSet<Warnings>();
        }
    
        public string Name { get; set; }
        public string Address { get; set; }
        public string Place { get; set; }
        public string Municipality { get; set; }
        public string PIB { get; set; }
        public string LegalID { get; set; }
        public System.DateTime CreationDate { get; set; }
        public string Activity { get; set; }
        public string Form { get; set; }
        public string ResponsiblePerson { get; set; }
        public string ResponsiblePersonPhone { get; set; }
        public string ResponsiblePersonMail { get; set; }
        public string PDV { get; set; }
        public string BookKeepingType { get; set; }
        public string Director { get; set; }
        public string Account { get; set; }
        public int EmployeesNumber { get; set; }
        public System.DateTime StartDate { get; set; }
        public int MainUserId { get; set; }
        public int SecondUserId { get; set; }
        public int Amount { get; set; }
        public string AmountCode { get; set; }
        public string Slava { get; set; }
        public System.DateTime BirthDate { get; set; }
        public System.DateTime ResponsiblePersonBirthDate { get; set; }
        public string DeliveryMethod { get; set; }
        public int CustomerID { get; set; }
        public string ActivityCode { get; set; }
        public string FormSubType { get; set; }
        public string AdditionalMails { get; set; }
        public Nullable<int> CourierDay { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> BillFirm { get; set; }
        public Nullable<System.DateTime> DateFrom { get; set; }
        public Nullable<System.DateTime> DateTo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Billings> Billings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Warnings> Warnings { get; set; }
    }
}
