//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportCMSLibrary
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DailyJobEntities : DbContext
    {
        public DailyJobEntities()
            : base("name=DailyJobEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Billings> Billings { get; set; }
        public virtual DbSet<Customers> Customers { get; set; }
        public virtual DbSet<ReportData> ReportData { get; set; }
        public virtual DbSet<ReportDataTypes> ReportDataTypes { get; set; }
        public virtual DbSet<ReportTypes> ReportTypes { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<Warnings> Warnings { get; set; }
        public virtual DbSet<AdminSettings> AdminSettings { get; set; }
        public virtual DbSet<AdminSettingsTypesDescriptions> AdminSettingsTypesDescriptions { get; set; }
        public virtual DbSet<ClientCosts> ClientCosts { get; set; }
        public virtual DbSet<ClientServices> ClientServices { get; set; }
        public virtual DbSet<Couriers> Couriers { get; set; }
        public virtual DbSet<CustomersChanges> CustomersChanges { get; set; }
        public virtual DbSet<CustomersReports> CustomersReports { get; set; }
        public virtual DbSet<CustomerTimes> CustomerTimes { get; set; }
        public virtual DbSet<DeletionReasons> DeletionReasons { get; set; }
        public virtual DbSet<Firms> Firms { get; set; }
        public virtual DbSet<Offers> Offers { get; set; }
        public virtual DbSet<PossibleCreations> PossibleCreations { get; set; }
        public virtual DbSet<RelatedCustomers> RelatedCustomers { get; set; }
        public virtual DbSet<Services> Services { get; set; }
        public virtual DbSet<Teams> Teams { get; set; }
        public virtual DbSet<Times> Times { get; set; }
        public virtual DbSet<Trace> Trace { get; set; }
    }
}
