//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportCMSLibrary
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DailyJobEntities : DbContext
    {
        public DailyJobEntities()
            : base("name=DailyJobEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Billing> Billings { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<ReportData> ReportDatas { get; set; }
        public virtual DbSet<ReportDataType> ReportDataTypes { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Warning> Warnings { get; set; }
        public virtual DbSet<AdminSetting> AdminSettings { get; set; }
        public virtual DbSet<AdminSettingsTypesDescription> AdminSettingsTypesDescriptions { get; set; }
        public virtual DbSet<ClientCost> ClientCosts { get; set; }
        public virtual DbSet<ClientService> ClientServices { get; set; }
        public virtual DbSet<Courier> Couriers { get; set; }
        public virtual DbSet<CustomersChanx> CustomersChanges { get; set; }
        public virtual DbSet<CustomersReport> CustomersReports { get; set; }
        public virtual DbSet<CustomerTime> CustomerTimes { get; set; }
        public virtual DbSet<Firm> Firms { get; set; }
        public virtual DbSet<Offer> Offers { get; set; }
        public virtual DbSet<PossibleCreation> PossibleCreations { get; set; }
        public virtual DbSet<ReportType> ReportTypes { get; set; }
        public virtual DbSet<Service> Services { get; set; }
        public virtual DbSet<Team> Teams { get; set; }
        public virtual DbSet<Time> Times { get; set; }
        public virtual DbSet<Trace> Traces { get; set; }
    }
}
