//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportCMSLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Firms
    {
        public int FirmId { get; set; }
        public string FirmName { get; set; }
        public string PIB { get; set; }
        public string Address { get; set; }
        public string AccountNumber { get; set; }
        public string PhoneNumber { get; set; }
        public string Mail { get; set; }
        public string LegalId { get; set; }
    }
}
