//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportCMSLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Offer
    {
        public int OfferId { get; set; }
        public string ContactPerson { get; set; }
        public string PIB { get; set; }
        public string Mail { get; set; }
        public string PhoneNumber { get; set; }
        public System.DateTime CreationDate { get; set; }
        public string ServiceId { get; set; }
        public string HeardFrom { get; set; }
        public bool IsSuccesful { get; set; }
        public string Impression { get; set; }
        public string BackInfo { get; set; }
        public int Amount { get; set; }
        public string AmountCurrency { get; set; }
        public bool IsOurCreation { get; set; }
        public string Note { get; set; }
        public int UserId { get; set; }
        public string Name { get; set; }
        public Nullable<bool> MakeRent { get; set; }
        public string CompanyType { get; set; }
        public string CompanySubType { get; set; }
    }
}
