//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportCMSLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class PossibleCreations
    {
        public int CreationId { get; set; }
        public string JobType { get; set; }
        public System.DateTime CreationDate { get; set; }
        public Nullable<System.DateTime> FormularDate { get; set; }
        public string Mail { get; set; }
        public string PhoneNumber { get; set; }
        public bool IsPaid { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public bool IsDone { get; set; }
        public bool IsMailSent { get; set; }
        public bool IsAnswerSuccesful { get; set; }
        public int ClientType { get; set; }
        public string Name { get; set; }
        public int UserId { get; set; }
        public Nullable<int> Status { get; set; }
        public string Note { get; set; }
        public Nullable<int> PaymentMethod { get; set; }
        public string PIB { get; set; }
        public Nullable<int> Amount { get; set; }
        public string CompanySubType { get; set; }
        public string JobDone { get; set; }
    }
}
