//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportCMSLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportData
    {
        public int ClientID { get; set; }
        public int ReportID { get; set; }
        public int TypeID { get; set; }
        public string ColumnName { get; set; }
        public bool IsDateRelated { get; set; }
        public int MonthlyPeriod { get; set; }
        public Nullable<int> Ordering { get; set; }
        public int Year { get; set; }
        public int Month { get; set; }
        public Nullable<System.DateTime> DateValue { get; set; }
        public string TextValue { get; set; }
        public Nullable<bool> BoolValue { get; set; }
    
        public virtual ReportDataTypes ReportDataTypes { get; set; }
    }
}
