//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportCMSLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trace
    {
        public System.DateTime Timestamp { get; set; }
        public string RequestUrl { get; set; }
        public Nullable<int> UserId { get; set; }
        public string Request { get; set; }
        public string Response { get; set; }
    }
}
