//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportCMSLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Warning
    {
        public int ID { get; set; }
        public Nullable<int> ClientID { get; set; }
        public Nullable<System.DateTime> WarningDate { get; set; }
        public Nullable<int> WarningType { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
